In [2]:
import numpy as np

In [2]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x / 2.0)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]
[0.5 1.  1.5]


In [3]:
A = np.array([[1, 2], [3, 4]])
print(A)
print(A.shape)
print(A.dtype)

[[1 2]
 [3 4]]
(2, 2)
int32


In [5]:
B = np.array([[3, 0], [0, 6]])
print(A + B)
print(A * B)

[[ 4  2]
 [ 3 10]]
[[ 3  0]
 [ 0 24]]


In [3]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
print(A * B)

[[10 40]
 [30 80]]


In [5]:
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)
print(X[0])
print(X[0][1])

[[51 55]
 [14 19]
 [ 0  4]]
[51 55]
55


In [6]:
for row in X:
  print(row)

[51 55]
[14 19]
[0 4]


In [9]:
for row in X:
  for column in row:
    print(column, end=' ')
  print('\n')

51 55 

14 19 

0 4 



In [10]:
print(X > 15)

[[ True  True]
 [False  True]
 [False False]]


In [11]:
print(X[X>15])

[51 55 19]
